name: weather-in
base: core24
version: '0.1'
summary: console tool to get weather status of a city
description: |
  Fetches and displays current weather information for a specified city
  using the OpenWeatherMap API. It requires an API key stored in ~/.apikey

grade: stable
confinement: strict
type: app

platforms:
  amd64:

parts:
  weather-in:
    plugin: python
    source-type: git
    source: https://github.com/devrim-ayyildiz/weather-in
    python-packages:
      - requests

apps:
  weather-in:
    command: bin/python3 $SNAP/weather-in/weather-in.py
